# Copyright [Your Organization] All Rights Reserved.
# SPDX-License-Identifier: [License Identifier]

---
description: |
  ### Document Name - DynamoDB-DeletionProtection_1.0.0

  ## What does this document do?
  This document enables deletion protection on specified DynamoDB tables to prevent accidental deletion.

  ## Input Parameters
  * Tables: (Required) List of DynamoDB tables to enable deletion protection.
  * AutomationAssumeRole: (Required) The ARN of the role that allows Automation to perform actions on your behalf.

  ## Output Parameters
  * Remediation.Output

schemaVersion: '0.3'
assumeRole: '{{ AutomationAssumeRole }}'
outputs:
  - Remediation.Output
parameters:
  Tables:
    type: StringList
    description: List of DynamoDB tables to enable deletion protection.
  AutomationAssumeRole:
    type: String
    description: (Required) The ARN of the role that allows Automation to perform actions on your behalf.
    allowedPattern: '^arn:(?:aws|aws-us-gov|aws-cn):iam::\d{12}:role/[\w+=,.@-]+$'
mainSteps:
  - name: ParseInput
    action: 'aws:executeScript'
    outputs:
      - Name: FindingId
        Selector: $.Payload.finding_id
        Type: String
      - Name: ProductArn
        Selector: $.Payload.product_arn
        Type: String
      - Name: AffectedTables
        Selector: $.Payload.affected_tables
        Type: StringList
      - Name: AccountId
        Selector: $.Payload.account_id
        Type: String
      - Name: TestMode
        Selector: $.Payload.testmode
        Type: Boolean
    inputs:
      InputPayload:
        Tables: '{{Tables}}'
        AutomationAssumeRole: '{{AutomationAssumeRole}}'
        parse_id_pattern: ''
        resource_index: 2
        expected_control_id:
        - 'DynamoDB.6'
      Runtime: python3.8
      Handler: parse_event
      Script: |-
        %%SCRIPT=common/parse_input.py%%
    isEnd: false

  - name: Remediation
    action: 'aws:executeAutomation'
    inputs:
      DocumentName: ASR-EnableDeletionProtectionDynamoDB
      RuntimeParameters:
        AccountId: '{{ParseInput.AccountId}}'
        AutomationAssumeRole: '{{ParseInput.AutomationAssumeRole}}'
        Tables: '{{ParseInput.AffectedTables}}'
        TestMode: '{{ParseInput.TestMode}}'
    isEnd: false

  - name: UpdateFinding
    action: 'aws:executeAwsApi'
    inputs:
      Service: securityhub
      Api: BatchUpdateFindings
      FindingIdentifiers:
      - Id: '{{ParseInput.FindingId}}'
        ProductArn: '{{ParseInput.ProductArn}}'
      Note:
        Text: 'DynamoDB tables deletion protection enabled'
        UpdatedBy: 'ASR-DeletionProtection_1.0.0'
      Workflow:
        Status: 'RESOLVED'
    description: Update finding
    isEnd: true
